# Numpy

In [326]:
# zero 
import numpy as np
zero_arr = np.array(10)
print(zero_arr)
print(type(zero_arr))
print(zero_arr.ndim,"Dimension")
print(zero_arr.dtype)


10
<class 'numpy.ndarray'>
0 Dimension
int64


In [327]:
one_arr = np.array([10,6,7])
print(one_arr)
print(type(one_arr))
print(one_arr.ndim,"Dimension")
print(one_arr.dtype)
print(one_arr.shape)

[10  6  7]
<class 'numpy.ndarray'>
1 Dimension
int64
(3,)


In [328]:
two_arr = np.array([[10,6,7]])
print(two_arr)
print(type(two_arr))
print(two_arr.ndim,"Dimension")
print(two_arr.dtype)
print(two_arr.shape)

[[10  6  7]]
<class 'numpy.ndarray'>
2 Dimension
int64
(1, 3)


In [329]:
two_arr = np.array([[10,6,7],[23,34,54]])
print(two_arr)
print(type(two_arr))
print(two_arr.ndim,"Dimension")
print(two_arr.dtype)
print(two_arr.shape)

[[10  6  7]
 [23 34 54]]
<class 'numpy.ndarray'>
2 Dimension
int64
(2, 3)


In [330]:
three_d = np.array([[[10,6,7],[23,34,54],[10,20,30]],
                    [[11,22,33],[21,23,33], [44,55,66]],
                    [[11,22,33],[21,23,33], [44,55,66]]])
print(three_d)
print(type(three_d))
print(three_d.ndim,"Dimension")
print(three_d.dtype)
print(three_d.shape)

[[[10  6  7]
  [23 34 54]
  [10 20 30]]

 [[11 22 33]
  [21 23 33]
  [44 55 66]]

 [[11 22 33]
  [21 23 33]
  [44 55 66]]]
<class 'numpy.ndarray'>
3 Dimension
int64
(3, 3, 3)


In [331]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [332]:
zero = np.zeros((2),dtype=int)
print(zero)
print(zero.ndim)
print(zero.dtype)

[0 0]
1
int64


In [333]:
zero = np.zeros((2,3,3),dtype=int)
print(zero)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [334]:
one = np.ones((2,2),dtype=int)
print(one)

[[1 1]
 [1 1]]


In [335]:
mat = np.array([2,"atul",None])
print(mat)
print(mat.dtype)

[2 'atul' None]
object


In [336]:
mat = np.array([2,"atul","mat"])
print(mat)
print(mat.dtype)


['2' 'atul' 'mat']
<U21


In [337]:
one_arr = np.array([10,6,54])
print(one_arr[0])
print(one_arr[1])
print(one_arr[2])
print(one_arr[-1])
print(one_arr[-2])

10
6
54
54
6


In [338]:
two_arr = np.array([[10,6,54],[11,22,33]])
print(two_arr[0])
print(two_arr[1])
print(two_arr[0][0])
print(two_arr[0][-1])
print(two_arr[1][1:2])

[10  6 54]
[11 22 33]
10
54
[22]


In [339]:
three_d = np.array([[[10,6,7],[23,34,54],[10,20,30]],
                     [[11,22,33], [21,23,33],[44,55,66]],
                                         [[11,22,33],[21,23,33], [44,55,66]]])

print(three_d[0])
print(three_d[0][0])
print(three_d[0][0][0])
print(three_d[0][0][::-1])

[[10  6  7]
 [23 34 54]
 [10 20 30]]
[10  6  7]
10
[ 7  6 10]


In [340]:
a = np.array([1,2,3])
b = np.array([5,4,6])
print(a+b)
# ye niche wali bhi same out put deti hai
add = np.add(a,b)
print(add)

[6 6 9]
[6 6 9]


In [341]:
a = np.array([1,2,3])
b = np.array([5,4,6])
print(a-b)

sub = np.subtract(a,b)
print(sub)



[-4 -2 -3]
[-4 -2 -3]


In [342]:
a = np.array([1,12,3])
a[0] = 44
a

array([44, 12,  3])

In [343]:
a = np.array([1,12,3])
a[0:2] = [66,77]
a

array([66, 77,  3])

In [344]:
a = np.array([[1,12,3],[6,7,8]])
a[0][0] = 11
a

array([[11, 12,  3],
       [ 6,  7,  8]])

In [345]:
a = np.array([[1,2,3],[6,7,8]])
a[1][1:] = [44,56]
a

array([[ 1,  2,  3],
       [ 6, 44, 56]])

In [346]:
arange = np.arange(40,dtype=float)
print(arange)
print(type(arange))
print(arange.ndim)
print(len(arange))
print(arange.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39.]
<class 'numpy.ndarray'>
1
40
40


In [347]:
arange = np.arange(12)
print(arange)
res_hap = arange.reshape((3,4))
print(res_hap)
print(res_hap.ndim, "Dimension")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2 Dimension


In [348]:
arange = np.arange(12)
print(arange)
res_hap = arange.reshape((2,2,3))
print(res_hap)
print(res_hap.ndim,"dimention")


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3 dimention


In [349]:
arange = np.arange(12)
print(arange)
res_hap = arange.reshape((2,3,2))
print(res_hap)
print(res_hap.ndim,"dimention")


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
3 dimention


In [350]:
a = np.array([[1,12,3],[6,7,8]],ndmin=5)
print(a)
print(a.ndim)

[[[[[ 1 12  3]
    [ 6  7  8]]]]]
5


In [351]:
a = np.array([[1,12,3],[6,7,8]],ndmin=50)
print(a)
print(a.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 1
                                                  12
                                                   3]
                                                 [ 6
                                                   7
                                                   8]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
50


In [352]:
lin = np.linspace(10,11,num=18)
print(lin)
lin_arr = lin.reshape(3,3,2)
print(lin_arr)

[10.         10.05882353 10.11764706 10.17647059 10.23529412 10.29411765
 10.35294118 10.41176471 10.47058824 10.52941176 10.58823529 10.64705882
 10.70588235 10.76470588 10.82352941 10.88235294 10.94117647 11.        ]
[[[10.         10.05882353]
  [10.11764706 10.17647059]
  [10.23529412 10.29411765]]

 [[10.35294118 10.41176471]
  [10.47058824 10.52941176]
  [10.58823529 10.64705882]]

 [[10.70588235 10.76470588]
  [10.82352941 10.88235294]
  [10.94117647 11.        ]]]


In [353]:
logspace = np.logspace(2,5,num=10)
logspace

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [354]:
linspace = np.linspace(10,11,num=20)


In [355]:
x = np.array([3,4,5,6,7,8])
mean = np.mean(x)
print(mean)
median = np.median(x)
print(median)
var = np.var(x)
print(var)
std = np.std(x)
print(std)

5.5
5.5
2.9166666666666665
1.707825127659933


In [356]:
x = np.array([3,4,5,6,7,8])

argmax = np.argmax(x)
argmin = np.argmin(x)
print(argmax,argmin)

5 0


In [357]:
x = np.array([3,4,5,6,7,8])

argmax = np.argmax(x)
argmin = np.argmin(x)
print(argmax,argmin)
min = np.min(x)
max =np.min(x)
print(min,max,)
Sum = np.sum(x)
print(Sum)

5 0
3 3
33


In [358]:
import numpy as np

a = np.array([10, 20, 30, 40])

b = a.view()
print(a)
print(b)


b[1] = 200
print(a)
print(b)




[10 20 30 40]
[10 20 30 40]
[ 10 200  30  40]
[ 10 200  30  40]


In [359]:
a = np.array([10, 20, 30, 40])
c = a.copy()
print(a)
print(c)

c[0] = 999
print(a)
print(c)

[10 20 30 40]
[10 20 30 40]
[10 20 30 40]
[999  20  30  40]


In [360]:
x = np.array([30,4,15,400,5,13])
print(x)

[ 30   4  15 400   5  13]


In [361]:
x[0] = 123
print(x)

[123   4  15 400   5  13]


In [362]:
copy_x = x.copy
print(x)

[123   4  15 400   5  13]


In [363]:
copy_x = x.copy()
print(copy_x)

[123   4  15 400   5  13]


In [364]:
copy_x

array([123,   4,  15, 400,   5,  13])

In [365]:
x = np.array([30,4,15,400,5,13])
print(x)

[ 30   4  15 400   5  13]


In [366]:
x[1] = 400
print(x)

[ 30 400  15 400   5  13]


In [367]:
view_x = x.view()
print(view_x)

[ 30 400  15 400   5  13]


In [368]:
view_x = x.view()
print(view_x)

[ 30 400  15 400   5  13]


In [369]:
view_x

array([ 30, 400,  15, 400,   5,  13])

# sorting

In [370]:
arr = np.array([[11,22,33],[56,54,43]])
sort = np.sort(arr,axis=None)
print(sort)

[11 22 33 43 54 56]


In [371]:
arr = np.array([[11,2,3],[56,570,58]])
print(arr)
two_arr_sort = np.sort(arr)
print(two_arr_sort)

[[ 11   2   3]
 [ 56 570  58]]
[[  2   3  11]
 [ 56  58 570]]


In [372]:
arr = np.array([[11,2,3],[56,570,58]])
print(arr)
two_arr_sort = np.sort(arr,axis=None)
print(two_arr_sort)

[[ 11   2   3]
 [ 56 570  58]]
[  2   3  11  56  58 570]


In [373]:
arr1 = np.array([11,2,3])
arr2 = np.array([3,2,5])
print(arr1)
print(arr2)

[11  2  3]
[3 2 5]


In [374]:
stack = np.stack((arr1,arr2),axis = 0)
print(stack)

[[11  2  3]
 [ 3  2  5]]


In [375]:
stack = np.stack((arr1,arr2),axis = 1)
print(stack)

[[11  3]
 [ 2  2]
 [ 3  5]]


In [380]:
arr = np.array([[11,3], [2,2], [3,5]])
print(arr)
arr_t = arr.T
print(arr_t)

[[11  3]
 [ 2  2]
 [ 3  5]]
[[11  2  3]
 [ 3  2  5]]


In [381]:
stack = np.stack((arr1,arr2),axis=1)
print(stack)

[[11  3]
 [ 2  2]
 [ 3  5]]


In [378]:
stack = np.stack((arr1,arr2), axis=0)
print(stack)

[[11  2  3]
 [ 3  2  5]]


In [ ]:
random = np.random.random()
print(random)


0.7357531310829788


In [387]:
rand = np.random.rand(3,2)
print(rand)

[[0.4619578  0.27271309]
 [0.10032905 0.02677673]
 [0.61387427 0.26311066]]


In [398]:
randint = np.random.randint(2,12, size=10)
print(randint)

[4 8 8 2 3 4 5 3 9 3]


In [404]:
np.random.seed(0)
randint = np.random.randint(2,12, size=10)
print(randint)

[ 7  2  5  5  9 11  5  7  4  6]
